import { Router } from 'express'
import { pool,withTransaction } from '../db/pool.js'
import { getBooking,toBooking } from '../bookings/queries.js'
import { requestHash } from '../holds/service.js'
import { requireAuth } from '../middleware/auth.js'
import { enqueueSeatChange } from '../realtime/outbox.js'

export const bookingsRouter=Router();bookingsRouter.use(requireAuth)

bookingsRouter.get('/',async(request,response,next)=>{try{const result=await pool.query(`SELECT b.*,e.slug,e.name event_name,e.venue,e.starts_at,e.timezone,
  coalesce(json_agg(json_build_object('id',es.seat_label,'section',bs.section,'price',bs.price_paise::numeric/100,'passengerName',bs.passenger_name,'cancelledAt',bs.cancelled_at) ORDER BY es.seat_label) FILTER(WHERE bs.event_seat_id IS NOT NULL),'[]') seats
  FROM bookings b JOIN events e ON e.id=b.event_id LEFT JOIN booking_seats bs ON bs.booking_id=b.id LEFT JOIN event_seats es ON es.id=bs.event_seat_id WHERE b.user_id=$1 GROUP BY b.id,e.id ORDER BY b.created_at DESC`,[request.user.id]);response.json({bookings:result.rows.map(toBooking)})}catch(error){next(error)}})

bookingsRouter.get('/:id',async(request,response,next)=>{try{const booking=await getBooking(pool,request.params.id,request.user.id);if(!booking)return response.status(404).json({code:'BOOKING_NOT_FOUND',message:'The booking could not be found.'});const payments=await pool.query('SELECT id,status,method,amount_paise,refunded_paise,created_at FROM payments WHERE booking_id=$1 ORDER BY created_at DESC',[booking.id]);let dto=toBooking(booking);if(!dto.seats.length){const held=await pool.query(`SELECT es.seat_label id,es.section,hs.price_paise::numeric/100 price FROM hold_seats hs JOIN event_seats es ON es.id=hs.event_seat_id WHERE hs.hold_id=$1 ORDER BY es.seat_label`,[booking.source_hold_id]);dto={...dto,seats:held.rows.map(row=>({...row,price:Number(row.price)}))}}response.json({booking:{...dto,payments:payments.rows.map(row=>({id:row.id,status:row.status,method:row.method,amount:Number(row.amount_paise)/100,refundedAmount:Number(row.refunded_paise)/100,createdAt:row.created_at}))}})}catch(error){next(error)}})

bookingsRouter.post('/:id/cancel',async(request,response,next)=>{try{const key=String(request.get('Idempotency-Key')||'').trim();if(key.length<8)return response.status(400).json({code:'IDEMPOTENCY_KEY_REQUIRED',message:'A valid Idempotency-Key header is required.'});const requested=Array.isArray(request.body?.seatIds)?[...new Set(request.body.seatIds.map(value=>String(value).toUpperCase()))].sort():[];const hash=requestHash(requested)
  const result=await withTransaction(async client=>{const prior=await client.query("SELECT request_hash,response_body FROM idempotency_records WHERE user_id=$1 AND operation=$2 AND key=$3 FOR UPDATE",[request.user.id,`CANCEL_BOOKING:${request.params.id}`,key]);if(prior.rowCount){if(prior.rows[0].request_hash!==hash){const error=new Error('This idempotency key was used for a different cancellation.');error.status=409;error.code='IDEMPOTENCY_KEY_REUSED';throw error}if(prior.rows[0].response_body)return prior.rows[0].response_body}else await client.query('INSERT INTO idempotency_records(user_id,operation,key,request_hash,expires_at) VALUES($1,$2,$3,$4,now()+interval \'24 hours\')',[request.user.id,`CANCEL_BOOKING:${request.params.id}`,key,hash])
    const booking=await client.query('SELECT b.*,e.starts_at,e.slug FROM bookings b JOIN events e ON e.id=b.event_id WHERE (b.id::text=$1 OR b.reference=$1) AND b.user_id=$2 FOR UPDATE OF b',[request.params.id,request.user.id]);if(!booking.rowCount)return null;const row=booking.rows[0];if(row.status==='CANCELLED')return{bookingId:row.id,status:'CANCELLED',cancelledSeatIds:[],refundAmount:0};if(row.status!=='CONFIRMED'){const error=new Error('Only confirmed bookings can be cancelled.');error.status=409;error.code='BOOKING_NOT_CANCELLABLE';throw error}if(new Date(row.starts_at).getTime()-Date.now()<=2*60*60*1000){const error=new Error('The cancellation window has closed.');error.status=409;error.code='CANCELLATION_WINDOW_CLOSED';throw error}
    const seats=await client.query('SELECT bs.event_seat_id,bs.price_paise,es.seat_label FROM booking_seats bs JOIN event_seats es ON es.id=bs.event_seat_id WHERE bs.booking_id=$1 AND bs.cancelled_at IS NULL FOR UPDATE OF bs',[row.id]);const selected=requested.length?seats.rows.filter(seat=>requested.includes(seat.seat_label)):seats.rows;const matched=new Set(selected.map(seat=>seat.seat_label));const unmatched=requested.filter(label=>!matched.has(label));if(unmatched.length){const error=new Error('Every requested seat must be active on this booking.');error.status=409;error.code='SEATS_NOT_CANCELLABLE';error.details={unmatchedSeatIds:unmatched};throw error}if(!selected.length){const error=new Error('No active seats matched this cancellation.');error.status=409;error.code='NO_CANCELLABLE_SEATS';throw error}const ids=selected.map(seat=>seat.event_seat_id);await client.query('UPDATE booking_seats SET cancelled_at=now() WHERE booking_id=$1 AND event_seat_id=ANY($2::uuid[])',[row.id,ids]);const remaining=seats.rows.length-selected.length;await client.query("UPDATE bookings SET status=CASE WHEN $2=0 THEN 'CANCELLED'::booking_status ELSE status END,cancelled_at=CASE WHEN $2=0 THEN now() ELSE cancelled_at END,updated_at=now() WHERE id=$1",[row.id,remaining]);const refund=selected.reduce((sum,seat)=>sum+Number(seat.price_paise),0);const payment=await client.query("SELECT * FROM payments WHERE booking_id=$1 AND status IN('SUCCESSFUL','PARTIALLY_REFUNDED') ORDER BY created_at DESC LIMIT 1 FOR UPDATE",[row.id]);if(payment.rowCount){const refunded=Number(payment.rows[0].refunded_paise)+refund;await client.query("UPDATE payments SET refunded_paise=$1,status=CASE WHEN $1>=amount_paise THEN 'REFUNDED'::payment_status ELSE 'PARTIALLY_REFUNDED'::payment_status END,updated_at=now() WHERE id=$2",[refunded,payment.rows[0].id])}const body={bookingId:row.id,status:remaining?'CONFIRMED':'CANCELLED',cancelledSeatIds:selected.map(seat=>seat.seat_label),remainingSeats:remaining,refundAmount:refund/100};await client.query('UPDATE idempotency_records SET response_status=200,response_body=$1 WHERE user_id=$2 AND operation=$3 AND key=$4',[body,request.user.id,`CANCEL_BOOKING:${request.params.id}`,key]);await enqueueSeatChange(client,row.slug,'booking-cancelled');return body})
  if(!result)return response.status(404).json({code:'BOOKING_NOT_FOUND',message:'The booking could not be found.'});response.json(result)}catch(error){next(error)}})
