import { Router } from 'express'
import { pool,withTransaction } from '../db/pool.js'
import { findEvent } from '../events/queries.js'
import { requireAuth } from '../middleware/auth.js'
import { promoteWaitlist } from '../waitlist/service.js'
import { enqueueSeatChange } from '../realtime/outbox.js'

export const waitlistRouter=Router();waitlistRouter.use(requireAuth)

waitlistRouter.post('/',async(request,response,next)=>{try{const requestedSeats=Number(request.body?.requestedSeats);const eventId=String(request.body?.eventId||'');if(!Number.isInteger(requestedSeats)||requestedSeats<1||requestedSeats>6)return response.status(400).json({code:'VALIDATION_ERROR',message:'Request between 1 and 6 seats.'});const result=await withTransaction(async client=>{const event=await findEvent(client,eventId,{shared:true});if(!event)return null;if(event.status!=='PUBLISHED'||new Date(event.starts_at)<=new Date()){const error=new Error('This event is not accepting waitlist entries.');error.status=409;error.code='WAITLIST_CLOSED';throw error}const existing=await client.query("SELECT * FROM waitlist_entries WHERE user_id=$1 AND event_id=$2 AND status IN('WAITING','OFFERED') FOR UPDATE",[request.user.id,event.id]);const entry=existing.rows[0]||await client.query('INSERT INTO waitlist_entries(user_id,event_id,requested_seats) VALUES($1,$2,$3) RETURNING *',[request.user.id,event.id,requestedSeats]).then(value=>value.rows[0]);await promoteWaitlist(client);const current=await client.query('SELECT w.*,h.expires_at offer_expires_at FROM waitlist_entries w LEFT JOIN holds h ON h.id=w.offered_hold_id WHERE w.id=$1',[entry.id]);return{entry:current.rows[0],created:!existing.rowCount}});if(!result)return response.status(404).json({code:'EVENT_NOT_FOUND',message:'The event could not be found.'});const entry=result.entry;response.status(result.created?201:200).json({entry:{id:entry.id,eventId,status:entry.status,requestedSeats:entry.requested_seats,position:entry.status==='WAITING'?Number(entry.position):null,offeredHoldId:entry.offered_hold_id,offerExpiresAt:entry.offer_expires_at}})}catch(error){next(error)}})

waitlistRouter.get('/',async(request,response,next)=>{try{const result=await pool.query(`SELECT w.*,e.slug,e.name,h.expires_at,
    count(*) FILTER(WHERE earlier.status='WAITING')::int+1 AS current_position
    FROM waitlist_entries w JOIN events e ON e.id=w.event_id LEFT JOIN holds h ON h.id=w.offered_hold_id
    LEFT JOIN waitlist_entries earlier ON earlier.event_id=w.event_id AND earlier.position<w.position AND earlier.status='WAITING'
    WHERE w.user_id=$1 GROUP BY w.id,e.id,h.id ORDER BY w.created_at DESC`,[request.user.id]);response.json({entries:result.rows.map(row=>({id:row.id,event:{id:row.slug,title:row.name},requestedSeats:row.requested_seats,status:row.status,position:row.status==='WAITING'?row.current_position:null,offeredHoldId:row.offered_hold_id,offerExpiresAt:row.expires_at,createdAt:row.created_at}))})}catch(error){next(error)}})

waitlistRouter.delete('/:id',async(request,response,next)=>{try{const removed=await withTransaction(async client=>{const result=await client.query("SELECT w.*,e.slug FROM waitlist_entries w JOIN events e ON e.id=w.event_id WHERE w.id=$1 AND w.user_id=$2 FOR UPDATE OF w",[request.params.id,request.user.id]);if(!result.rowCount)return null;const row=result.rows[0];if(row.offered_hold_id){await client.query('DELETE FROM seat_claims WHERE hold_id=$1',[row.offered_hold_id]);const released=await client.query("UPDATE holds SET status='RELEASED',updated_at=now() WHERE id=$1 AND status='ACTIVE' RETURNING id",[row.offered_hold_id]);if(released.rowCount)await enqueueSeatChange(client,row.slug,'hold-released')}await client.query("UPDATE waitlist_entries SET status='CANCELLED',updated_at=now() WHERE id=$1",[row.id]);return true});if(!removed)return response.status(404).json({code:'WAITLIST_ENTRY_NOT_FOUND',message:'The waitlist entry could not be found.'});response.status(204).end()}catch(error){next(error)}})
