import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Layout, PageHeader, Spinner, StatusBadge, useToast } from '../components'
import { apiRequest } from '../api'
import { events, initialSeats } from '../data'

function LegacyAdminDashboard(){return null}

function EventTable({summary=false}){return <div className="table-responsive"><table className="table admin-table align-middle"><thead><tr><th>Event</th><th>Date</th><th>Total seats</th><th>Available</th>{summary&&<th>Active holds</th>}<th>Confirmed</th><th>Status</th>{!summary&&<th/>}</tr></thead><tbody>{events.map((event,index)=><tr key={event.id}><td><strong>{event.title}</strong><small>{event.venue}</small></td><td>{event.date}</td><td>{event.total}</td><td><strong className="text-success">{event.available}</strong></td>{summary&&<td>{[8,0,0][index]}</td>}<td>{event.total-event.available-[8,0,0][index]}</td><td><StatusBadge status={event.status}/></td>{!summary&&<td className="text-end"><Link className="btn btn-sm btn-light" to={`/admin/events/${event.id}/edit`}>Edit</Link></td>}</tr>)}</tbody></table></div>}

function LegacyAdminEvents(){return null}

export function EventForm(){const{id}=useParams();const editing=Boolean(id);const showToast=useToast();const[busy,setBusy]=useState(false);const[event,setEvent]=useState(null);useEffect(()=>{if(id)apiRequest(`/v1/events/${id}`).then(data=>setEvent(data.event)).catch(err=>showToast(err.message,'error'))},[id]);async function submit(e){e.preventDefault();setBusy(true);try{await apiRequest(editing?`/v1/admin/events/${id}`:'/v1/admin/events',{method:editing?'PATCH':'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});showToast(editing?'Event updated.':'Event created.')}catch(err){showToast(err.message,'error')}finally{setBusy(false)}}const starts=event?new Date(event.startsAt):null;return <Layout admin><main id="main-content" className="container page-wrap admin-page"><div className="form-page-heading"><span className="eyebrow">Event management</span><h1>{editing?'Edit event':'Create an event'}</h1><p>Manage public details, schedule, and booking status.</p></div>{editing&&!event?<Spinner label="Loading event…"/>:<form className="content-card admin-form" onSubmit={submit}><div className="form-section"><h2>Event details</h2><div className="row g-4"><div className="col-12"><label className="form-label" htmlFor="eventName">Event name</label><input className="form-control" id="eventName" name="name" defaultValue={event?.title} required/></div><div className="col-md-7"><label className="form-label" htmlFor="venue">Venue</label><input className="form-control" id="venue" name="venue" defaultValue={event?.venue} required/></div><div className="col-md-5"><label className="form-label" htmlFor="status">Status</label><select className="form-select" id="status" name="status" defaultValue={event?.status||'DRAFT'}><option>DRAFT</option><option>PUBLISHED</option><option>CANCELLED</option><option>COMPLETED</option></select></div><div className="col-12"><label className="form-label" htmlFor="description">Description</label><textarea className="form-control" id="description" name="description" rows="4" defaultValue={event?.description}/></div></div></div><div className="form-section"><h2>Schedule</h2><div className="row g-4"><div className="col-md-6"><label className="form-label" htmlFor="eventDate">Date</label><input className="form-control" id="eventDate" name="date" type="date" defaultValue={starts?.toISOString().slice(0,10)} required/></div><div className="col-md-6"><label className="form-label" htmlFor="eventTime">Time</label><input className="form-control" id="eventTime" name="time" type="time" defaultValue={starts?.toISOString().slice(11,16)||'19:00'} required/></div></div></div><div className="form-actions"><Link to="/admin/events" className="btn btn-light">Cancel</Link><button className="btn btn-primary" disabled={busy}>{busy?<Spinner label="Saving event…"/>:editing?'Save changes':'Create event'}</button></div></form>}</main></Layout>}

function LegacyAdminSeats(){return null}

export function ConcurrencyDemo(){const showToast=useToast();const[busy,setBusy]=useState(false);const[result,setResult]=useState(null);async function run(e){e.preventDefault();setBusy(true);const form=Object.fromEntries(new FormData(e.currentTarget));try{const data=await apiRequest('/v1/admin/concurrency-demo',{method:'POST',body:JSON.stringify({eventId:'techfest-live',seatId:form.seatId,concurrentRequests:Number(form.requests)})});setResult(data);showToast('Contention test completed.')}catch(err){showToast(err.message,'error')}finally{setBusy(false)}}return <Layout admin><main id="main-content" className="container page-wrap admin-page"><PageHeader eyebrow="Engineering demonstration" heading="Concurrency demo" description="Ask the backend to contend for one seat, then display its authoritative result."/><div className="demo-layout"><section className="content-card"><div className="demo-warning"><span>i</span><p><strong>Live database test</strong>Temporary test customers contend through real PostgreSQL transactions and are cleaned up afterward.</p></div><form onSubmit={run}><div className="row g-3 mb-4"><div className="col-sm-6"><label className="form-label" htmlFor="demoSeat">Seat</label><select className="form-select" id="demoSeat" name="seatId"><option>A1</option><option>A2</option><option>B3</option></select></div><div className="col-sm-6"><label className="form-label" htmlFor="requests">Concurrent requests</label><input className="form-control" id="requests" name="requests" type="number" min="2" max="50" defaultValue="20"/></div></div><button className="btn btn-primary w-100" disabled={busy}>{busy?<Spinner label="Running test…"/>:'Run contention test'}</button></form></section><section className="content-card demo-result">{result?<><div className="result-heading"><div><span className="eyebrow">Test result</span><h2>Single-winner invariant</h2></div><span className="invariant-badge">{result.invariantPassed?'✓ PASSED':'! FAILED'}</span></div><div className="result-metrics"><div><span>Requests</span><strong>{result.requests}</strong></div><div><span>Successful holds</span><strong>{result.successfulHolds}</strong></div><div><span>Conflicts</span><strong>{result.conflicts}</strong></div><div><span>Claims in DB</span><strong>{result.activeHolds}</strong></div></div></>:<div className="result-empty"><h2>Ready to test</h2><p>Choose an available seat and run simultaneous hold attempts.</p></div>}</section></div></main></Layout>}

function AdminEventRows({items,summary=false}){return <div className="table-responsive"><table className="table admin-table align-middle"><thead><tr><th>Event</th><th>Starts</th><th>Total</th><th>Available</th><th>Confirmed</th><th>Status</th>{!summary&&<th/>}</tr></thead><tbody>{items.map(event=><tr key={event.id}><td><strong>{event.title}</strong><small>{event.venue}</small></td><td>{new Date(event.startsAt).toLocaleString('en-IN')}</td><td>{event.total}</td><td><strong className="text-success">{event.available}</strong></td><td>{Math.max(0,event.total-event.available)}</td><td><StatusBadge status={event.status}/></td>{!summary&&<td><Link className="btn btn-sm btn-light" to={`/admin/events/${event.id}/edit`}>Edit</Link></td>}</tr>)}</tbody></table></div>}

export function AdminDashboard(){const[metrics,setMetrics]=useState(null);const[items,setItems]=useState([]);useEffect(()=>{Promise.all([apiRequest('/v1/admin/dashboard'),apiRequest('/v1/admin/events')]).then(([dashboard,eventData])=>{setMetrics(dashboard.metrics);setItems(eventData.events)})},[]);const cards=metrics?[['◫','Active events',metrics.active_events,'Published and upcoming'],['✓','Confirmed bookings',metrics.confirmed_bookings,'Current inventory'],['◷','Active holds',metrics.active_holds,'Live temporary claims'],['⌛','Waiting customers',metrics.waiting_customers,'Across all events']]:[];return <Layout admin><main id="main-content" className="container page-wrap admin-page"><PageHeader eyebrow="Operations overview" heading="LeaseLock Admin" description="Live PostgreSQL inventory and booking activity." action={{to:'/admin/events/new',label:'Create event'}}/><section className="metric-grid">{cards.map(([icon,label,value,note])=><article key={label}><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</section><section className="admin-section"><div className="section-heading"><div><h2>Event inventory</h2><p>Current authoritative availability.</p></div><Link to="/admin/events">Manage all events →</Link></div><AdminEventRows items={items} summary/></section></main></Layout>}

export function AdminEvents(){const[query,setQuery]=useState('');const[items,setItems]=useState([]);useEffect(()=>{apiRequest('/v1/admin/events').then(data=>setItems(data.events))},[]);const visible=items.filter(event=>`${event.title} ${event.venue}`.toLowerCase().includes(query.toLowerCase()));return <Layout admin><main id="main-content" className="container page-wrap admin-page"><PageHeader eyebrow="Event management" heading="Events" description="Create, update, and inspect reservable inventory." action={{to:'/admin/events/new',label:'+ Create event'}}/><section className="admin-section"><div className="admin-toolbar"><input className="form-control search-control" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search events"/></div><AdminEventRows items={visible}/></section></main></Layout>}

export function AdminSeats(){const[eventsList,setEventsList]=useState([]);const[eventId,setEventId]=useState('techfest-live');const[seats,setSeats]=useState([]);const[query,setQuery]=useState('');const[filter,setFilter]=useState('all');const[busy,setBusy]=useState(false);const showToast=useToast();useEffect(()=>{apiRequest('/v1/admin/events').then(data=>setEventsList(data.events))},[]);async function refresh(){setBusy(true);try{const data=await apiRequest(`/v1/admin/seats?eventId=${encodeURIComponent(eventId)}`);setSeats(data.seats);showToast('Seat status refreshed.')}catch(err){showToast(err.message,'error')}finally{setBusy(false)}}useEffect(()=>{refresh()},[eventId]);const rows=seats.filter(seat=>(filter==='all'||seat.status===filter)&&seat.id.toLowerCase().includes(query.toLowerCase()));return <Layout admin><main id="main-content" className="container page-wrap admin-page"><PageHeader eyebrow="Inventory inspection" heading="Seat status" description="Live server-reported state for every seat."/><section className="admin-section"><div className="admin-toolbar"><select className="form-select event-select" value={eventId} onChange={event=>setEventId(event.target.value)}>{eventsList.map(event=><option key={event.id} value={event.id}>{event.title}</option>)}</select><div className="d-flex gap-2"><input className="form-control search-control" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search seat"/><button className="btn btn-outline-secondary" onClick={refresh} disabled={busy}>{busy?'Refreshing…':'↻ Refresh'}</button></div></div><div className="filter-pills compact">{['all','AVAILABLE','HELD','RESERVED','UNAVAILABLE'].map(value=><button key={value} className={filter===value?'active':''} onClick={()=>setFilter(value)}>{value}</button>)}</div><div className="table-responsive"><table className="table admin-table"><thead><tr><th>Seat</th><th>Section</th><th>Price</th><th>Status</th><th>Hold expires</th></tr></thead><tbody>{rows.map(seat=><tr key={seat.id}><td><strong>{seat.id}</strong></td><td>{seat.section}</td><td>₹{seat.price}</td><td><StatusBadge status={seat.status}/></td><td>{seat.expires_at?new Date(seat.expires_at).toLocaleTimeString():'—'}</td></tr>)}</tbody></table></div></section></main></Layout>}
